# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  leftjoint_1:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint_2:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint_3:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint_4:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint_5:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint_6:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint_7:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint_1:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint_2:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint_3:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint_4:
    has_velocity_limits: true
    max_velocity: 1.3963
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint_5:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint_6:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint_7:
    has_velocity_limits: true
    max_velocity: 1.2218
    has_acceleration_limits: false
    max_acceleration: 0